//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyerWiseOrderStatus.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERS
    {
        public int CUSTOMER_ID { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_DESC { get; set; }
        public int LOCATION_ID { get; set; }
        public int STRIP_COLOUR { get; set; }
        public byte LATE_ALLOWED { get; set; }
        public byte PRIORITY { get; set; }
        public int PLAN_GROUP_ID { get; set; }
        public byte DIST_CENTRE_DAYS { get; set; }
        public int CHANGE_ID { get; set; }
        public int CUSTOMER_GROUP { get; set; }
        public byte UPLIFT_PERCENT { get; set; }
    }
}
