//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyerWiseOrderStatus.Data_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FR_PJLEntities : DbContext
    {
        public FR_PJLEntities()
            : base("name=FR_PJLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMERS> CUSTOMERS { get; set; }
        public virtual DbSet<ORDER_DELIVERIES> ORDER_DELIVERIES { get; set; }
        public virtual DbSet<ORDER_USER_DEFINED_VALUES> ORDER_USER_DEFINED_VALUES { get; set; }
        public virtual DbSet<ORDERS> ORDERS { get; set; }
    }
}
