//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuyerWiseOrderStatus.Data_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DELIVERIES
    {
        public int ORDER_ID { get; set; }
        public System.DateTime DEL_DATE { get; set; }
        public int DEL_ID { get; set; }
        public System.DateTime ORIG_DEL_DATE { get; set; }
        public int DEL_QTY { get; set; }
        public string DEL_REF { get; set; }
        public int EXTERNAL_ID { get; set; }
        public int START_DATE { get; set; }
        public int END_DATE { get; set; }
        public int TRANS_METHOD_ID { get; set; }
        public System.DateTime EXTN_DEL_DATE { get; set; }
        public string EXTN_DEL_NOTE { get; set; }
    }
}
